### ISSUE TITLE
2. Механизм шаблонов

### ISSUE THREAD

**Issue by vpvtima** [vsptima/front#2]
Придумать простейший механизм шаблонов, для облегчения работы с отдельной страницей. 
Все шаблоны должны быть разбиты на следующие части
- общие,
- повторяющиеся,
- уникальные

Пример:
> $pageTitle = 'название текущей страницы';
> Подключаем общий верх
> Уникальная часть страницы
> Подключаем общий низ

Внутри общих элементов шаблонов могут быть повторяющиеся части

**Comment by vsptima** [comment]
**Переменные для страницы.**
- pageTitle
- pageDescription
- pageAuthor
- pageOgImage
