### ISSUE TITLE
4. Страницы сайта

### ISSUE THREAD

**Issue by vpvtima** [vsptima/front#4]
* Обо мне
* Обратная связь
* Фотогалерея
* Хобби
* Жаргон
* Опыт
* Термины
* GitHub

**Comment by vsptima** [comment]
Обо мне - about.php = sidebar
Обратная связь - feedback.php = sidebar
Фотогаллерея - gallery.php = not sidebar
Хобби - hobby.php = sidebar
Жаргон - jargon.php = sidebar
Опыт - skill.php = sidebar
Термины - terms.php = not sidebar
GitHub - github.php = sidebar
