### ISSUE TITLE
8. Хранилища данных

### ISSUE THREAD

**Issue by vsptima** [vsptima/front#8]
## В текстовых файлах
- term --> xml
- github --> json
- gallery --> php
- jargon --> csv
- skill --> txt

## В SQLite
- hobby

**Comment by vpvtima** [comment]
Надо еще добавить массив и объект javascript

**Comment by vsptima** [comment]
- http://www.sqlitetutorial.net/sqlite-sample-database/
- http://adatum.ru/primery-zaprosov-sqlite-s-pdo.html
- http://i-novice.net/sqlite-legkij-sql/
